name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}} 
        password: ${{secrets.DOCKER_PASSWORD}}
        login-server: ${{secrets.DOCKER_CONTAINER_REGISTRY}}
        
    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file scr/Api/Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/newsapi:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/newsapi:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/newsapi:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/newsapi
